export default {
    extends: ["@commitlint/config-conventional"],
    rules: {
        "type-enum": [
            2,
            "always",
            [
                "feat",
                "fix",
                "refactor",
                "docs",
                "style",
                "test",
                "chore",
                "perf",
                "build",
                "ci",
                "revert",
                "env",
                "security",
                "hotfix",
            ],
        ],
        "scope-enum": [
            2,
            "always",
            [
                "ui",
                "button",
                "modal",
                "form",
                "api",
                "auth",
                "database",
                "security",
                "routing",
                "deps",
                "config",
                "docs",
                "test",
                "unit",
                "integration",
                "build",
                "ci",
                "env",
                "performance",
                "error",
                "eslint",
                "util",
                "helper",
            ],
        ],
    },
};
